// TSB Hub 0.8.31 - clear finance journal and force mobile render.
(function(){
  const DAY=86400000;
  const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''));
  const money=v=>moneyNumber(v)||0;
  const planned=x=>x.status==='planned';
  const today=()=>toISODate(new Date());
  let lastRenderAt=0;
  function plusDays(iso,n){const d=new Date(`${iso}T00:00:00`);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
  function diffDays(a,b){return Math.max(0,Math.round((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/DAY))}
  function nowTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
  function futureItems(list,base=today()){return list.filter(planned).filter(x=>!validDate(x.date)||x.date>=base).sort((a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999')))}
  function nextIncome(ctx,base=today()){return futureItems(ctx.incomes,base).find(x=>validDate(x.date))||null}
  function horizonDate(ctx,base=today()){return nextIncome(ctx,base)?.date||plusDays(base,7)}
  function obligationsUntil(ctx,end,base=today()){return futureItems(ctx.obligations,base).filter(x=>!validDate(x.date)||x.date<=end)}
  function calcFinance(ctx,summary,base=today()){
    const available=money(ctx.availableBalance),end=horizonDate(ctx,base);
    const obligations=obligationsUntil(ctx,end,base),required=obligations.reduce((s,x)=>s+money(x.amount),0);
    const free=available-required,days=Math.max(1,diffDays(base,end)+1),dayLimit=Math.floor(free/days),leftToday=dayLimit-money(summary.total);
    let status='Нормально',tone='ok',note=`До ${shortDate(end)} можно примерно ${formatRub(String(Math.max(0,dayLimit)))} в день.`;
    if(!ctx.availableBalance){status='Нет баланса';tone='empty';note='Укажи деньги на карте, чтобы расчёт стал полезным.'}
    else if(free<0){status='Не хватает';tone='danger';note=`До ${shortDate(end)} не хватает ${formatRub(String(Math.abs(free)))}.`}
    else if(dayLimit<500){status='Жёстко экономить';tone='danger';note=`Лимит очень низкий до ${shortDate(end)}.`}
    else if(dayLimit<1000){status='Осторожно';tone='warn';note=`Лучше держать траты около ${formatRub(String(dayLimit)))} в день.`}
    return{end,required,free,dayLimit,leftToday,status,tone,note};
  }
  function miniExpenseForm(){
    const opts=FINANCE_CATEGORIES.map(c=>`<option value="${escapeHTML(c.value)}">${escapeHTML(c.label)}</option>`).join('');
    return `<form class="finance-mini-form" data-mini-finance-form><label>Сумма<input name="amount" required inputmode="decimal" placeholder="250"></label><label>Категория<select name="category">${opts}</select></label><button class="primary-button" type="submit">Записать трату</button></form>`;
  }
  function expenseList(iso){
    const day=getFinance(iso),items=[...day.expenses].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));
    if(!items.length)return day.noExpenses?'<div class="empty">Сегодня отмечено без трат.</div>':'<div class="empty">Сегодня трат пока нет.</div>';
    return items.slice(0,6).map(x=>`<article class="finance-card"><div class="item-top"><div><div class="badge-row"><span class="badge important">${escapeHTML(getFinanceCategoryLabel(x.category))}</span>${x.time?`<span class="badge">${escapeHTML(x.time)}</span>`:''}</div><h3>${formatRub(x.amount)}</h3></div><div class="actions"><button class="danger-button" data-mini-expense-delete="${x.id}">Отменить</button></div></div></article>`).join('')+(items.length>6?'<div class="muted finance-summary-line">Показаны последние 6 трат.</div>':'');
  }
  function eventCard(entry){const item=entry.item,type=entry.type,title=escapeHTML(item.title||(type==='income'?'Поступление':'Оплата'));return `<article class="finance-event ${type}"><div><strong>${type==='income'?'+':'−'} ${title}</strong><div class="muted">${item.date?shortDate(item.date):'без даты'} · ${formatRub(item.amount)}</div></div><button class="ghost-button small" data-finance-plan-complete="${item.id}" data-plan-type="${type}">${type==='income'?'Получено':'Оплачено'}</button></article>`}
  function eventsList(ctx){const base=today();const rows=[...futureItems(ctx.obligations,base).map(item=>({type:'obligation',item})),...futureItems(ctx.incomes,base).map(item=>({type:'income',item}))].sort((a,b)=>String(a.item.date||'9999').localeCompare(String(b.item.date||'9999'))).slice(0,5);return rows.length?rows.map(eventCard).join(''):'<div class="empty">Ближайших поступлений и оплат нет.</div>'}
  const opLabels={expense:'трата',income:'поступление',obligation:'обязательная оплата',adjustment:'корректировка'};
  function operationJournal(ctx){const ops=[...ctx.operations].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,80);if(!ops.length)return '<div class="empty">Журнал пока пустой.</div>';return ops.map(op=>`<article class="finance-card operation-card ${op.type==='adjustment'?'technical':''}"><div class="item-top"><div><div class="badge-row"><span class="badge secondary">${opLabels[op.type]||'операция'}</span><span class="badge">${shortDate(op.date)}</span></div><h3>${money(op.amount)>0?'+':''}${formatRub(op.amount)}</h3><p class="muted">${escapeHTML(op.title||'Операция')}${op.comment?` · ${escapeHTML(op.comment)}`:''}</p></div><div class="actions operation-actions"><button class="ghost-button" data-op-hide="${op.id}">Скрыть</button><button class="danger-button" data-op-rollback="${op.id}">Откатить</button></div></div></article>`).join('')}
  function moreBlock(ctx){return `<details class="card collapsible-list finance-more"><summary>Управление</summary><section class="mini-inner"><h3>Баланс и резерв</h3><form class="form-grid finance-context" data-mini-balance-form><label>На карте<input name="availableBalance" inputmode="decimal" placeholder="Напр. 12500" value="${escapeHTML(ctx.availableBalance||'')}"></label><label>Резерв<input name="reserveBalance" inputmode="decimal" placeholder="Не трогать каждый день" value="${escapeHTML(ctx.reserveBalance||'')}"></label><button class="primary-button" type="submit">Сохранить</button></form></section><details class="collapsible-list" data-details-key="finance-add-plans"><summary>Добавить поступление / оплату</summary>${renderFinancePlanForm('income')}${renderFinancePlanForm('obligation')}</details><details class="collapsible-list" data-details-key="finance-journal"><summary>Журнал операций · ${ctx.operations.length}</summary><p class="muted">Скрыть — удалить только запись. Откатить — отменить влияние операции на баланс и связанные записи.</p><div class="finance-list">${operationJournal(ctx)}</div></details></details>`}
  function renderMiniFinance(){const root=$('#tab-finance');if(!root)return;lastRenderAt=Date.now();const base=today(),summary=getFinanceSummary(base),ctx=getFinanceContext(),calc=calcFinance(ctx,summary,base);root.innerHTML=`<section class="card finance-mini-hero finance-state-${calc.tone}"><div class="finance-status-row"><span class="finance-status-pill">${calc.status}</span><span class="muted">${shortDate(base)} → ${shortDate(calc.end)}</span></div><h2>Финансы</h2><p class="muted">${calc.note}</p><div class="finance-life-grid main-grid"><div class="finance-life-stat main"><span class="muted">Лимит на день</span><b>${ctx.availableBalance?formatRub(String(Math.max(0,calc.dayLimit))):'—'}</b></div><div class="finance-life-stat"><span class="muted">Осталось сегодня</span><b>${ctx.availableBalance?formatRub(String(calc.leftToday)):'—'}</b></div><div class="finance-life-stat"><span class="muted">На карте</span><b>${ctx.availableBalance?formatRub(ctx.availableBalance):'—'}</b></div><div class="finance-life-stat"><span class="muted">Свободно на жизнь</span><b>${ctx.availableBalance?formatRub(String(calc.free)):'—'}</b></div><div class="finance-life-stat"><span class="muted">Резерв</span><b>${ctx.reserveBalance?formatRub(ctx.reserveBalance):'—'}</b></div><div class="finance-life-stat"><span class="muted">Обязательное скоро</span><b>${formatRub(String(calc.required))}</b></div></div></section><section class="card finance-mini-expense"><div class="card-title-row"><div><h2>Быстрая трата</h2><p class="muted">Запись всегда идёт в сегодняшний день.</p></div></div>${miniExpenseForm()}<button class="ghost-button finance-no-expenses ${getFinance(base).noExpenses?'active':''}" type="button" data-mini-no-expenses>${getFinance(base).noExpenses?'✓ Сегодня не было трат':'Сегодня не было трат'}</button><details class="collapsible-list" data-details-key="finance-today-expenses" open><summary>Сегодняшние траты · ${summary.count}</summary><div class="finance-list">${expenseList(base)}</div></details></section><section class="card finance-mini-next"><div class="card-title-row"><div><h2>Ближайшее</h2><p class="muted">Оплаты и поступления по датам.</p></div></div><div class="finance-events-list">${eventsList(ctx)}</div></section>${moreBlock(ctx)}`;bindCommonActions(root);bindMiniFinance(root,base)}
  function rollbackOperation(op){const ctx=getFinanceContext(),amount=money(op.amount);addAvailableBalance(-amount);if(op.type==='expense'&&op.sourceId&&app.finance?.[op.date]?.expenses)app.finance[op.date].expenses=app.finance[op.date].expenses.filter(x=>x.id!==op.sourceId);if(op.type==='income'&&op.sourceId){const item=ctx.incomes.find(x=>x.id===op.sourceId);if(item){item.status='planned';item.completedAt=''}}if(op.type==='obligation'&&op.sourceId){const item=ctx.obligations.find(x=>x.id===op.sourceId);if(item){item.status='planned';item.completedAt=''}}ctx.operations=ctx.operations.filter(x=>x.id!==op.id)}
  function bindMiniFinance(root,base){const qsa=s=>Array.from(root.querySelectorAll(s));qsa('[data-mini-finance-form]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),amount=normalizeMoneyInput(fd.get('amount'));if(!amount)return;const expense={id:uid('exp'),amount,category:normalizeFinanceCategory(fd.get('category')),reason:'',comment:'',time:nowTime(),createdAt:new Date().toISOString()};const day=getFinance(base);day.noExpenses=false;day.expenses.push(expense);addAvailableBalance(-money(amount));addFinanceOperation('expense',-money(amount),getFinanceCategoryLabel(expense.category),'',expense.id,base);markChanged();showToast('Трата добавлена')});qsa('[data-mini-no-expenses]').forEach(btn=>btn.onclick=()=>{const day=getFinance(base);if(day.expenses.length)return;day.noExpenses=!day.noExpenses;markChanged();showToast(day.noExpenses?'День отмечен без трат':'Отметка без трат снята')});qsa('[data-mini-expense-delete]').forEach(btn=>btn.onclick=async()=>{if(!await openConfirmDialog('Отменить трату?'))return;const day=getFinance(base),exp=day.expenses.find(x=>x.id===btn.dataset.miniExpenseDelete);if(exp)addAvailableBalance(money(exp.amount));day.expenses=day.expenses.filter(x=>x.id!==btn.dataset.miniExpenseDelete);getFinanceContext().operations=getFinanceContext().operations.filter(op=>op.sourceId!==btn.dataset.miniExpenseDelete);markChanged();showToast('Трата отменена')});qsa('[data-mini-balance-form]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),ctx=getFinanceContext();ctx.availableBalance=normalizeSignedMoneyInput(fd.get('availableBalance'));ctx.reserveBalance=normalizeMoneyInput(fd.get('reserveBalance'));markChanged();showToast('Баланс сохранён без записи в журнал')});qsa('[data-op-hide]').forEach(btn=>btn.onclick=()=>{const ctx=getFinanceContext();ctx.operations=ctx.operations.filter(op=>op.id!==btn.dataset.opHide);markChanged();showToast('Запись скрыта, баланс не изменён')});qsa('[data-op-rollback]').forEach(btn=>btn.onclick=async()=>{const ctx=getFinanceContext(),op=ctx.operations.find(x=>x.id===btn.dataset.opRollback);if(!op)return;if(!await openConfirmDialog({title:'Откатить операцию?',message:'Будет отменено влияние этой операции на баланс. Для трат также удалится связанная запись, для поступлений/оплат статус вернётся в план.',confirmText:'Откатить',danger:true}))return;rollbackOperation(op);markChanged();showToast('Операция откачена')})}
  function forceIfFinance(){if(document.body?.dataset.activeTab==='finance')renderMiniFinance()}
  function install(){try{renderFinance=renderMiniFinance}catch(e){window.renderFinance=renderMiniFinance}forceIfFinance();setTimeout(forceIfFinance,150);setTimeout(forceIfFinance,500)}
  document.addEventListener('DOMContentLoaded',install);window.addEventListener('load',install);document.addEventListener('click',e=>{if(e.target.closest('[data-tab],[data-tab-target]'))setTimeout(forceIfFinance,80)});
  let tries=0;const timer=setInterval(()=>{tries+=1;if(document.body?.dataset.activeTab==='finance'&&Date.now()-lastRenderAt>400)renderMiniFinance();if(tries>16)clearInterval(timer)},250);
})();
