'use strict';
const assert = require('node:assert/strict'); const test = require('node:test'); const fs = require('node:fs'); const path = require('node:path');
const root = path.resolve(__dirname, '..'); const read = file => fs.readFileSync(path.join(root, file), 'utf8');
test('migrations contain only account/state/audit/rate-limit tables', () => { const sql = `${read('migrations/0001_backend.sql')}\n${read('migrations/0002_rate_limits.sql')}`; assert.deepEqual([...sql.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/gi)].map(x => x[1]), ['users', 'user_state', 'audit_events', 'rate_limits']); assert.doesNotMatch(sql, /provider_credentials|provider_preferences|ciphertext|\biv\b|key_version/i); });
test('environment has no server credential secrets', () => { assert.doesNotMatch(read('.dev.vars.example'), /^AI_CREDENTIAL_KEK=|^AI_KEY_VERSION=/m); });
test('provider credential/preferences route files are absent', () => { for (const file of ['functions/api/v1/providers/index.js', 'functions/api/v1/providers/[provider]/credential.js', 'functions/api/v1/preferences.js']) assert.equal(fs.existsSync(path.join(root, file)), false, `unexpected route: ${file}`); });
test('repositories expose only account/state/audit operations', () => { const source = read('functions/_lib/repositories.mjs'); for (const name of ['upsertEncryptedCredential', 'listCredentialMetadata', 'deleteCredential', 'setProviderPreference', 'getProviderPreference']) assert.doesNotMatch(source, new RegExp(`(?:export\\s+)?(?:async\\s+)?${name}\\s*\\(`), `unexpected repository method: ${name}`); assert.doesNotMatch(source, /provider_credentials|provider_preferences/i); });
test('crypto has primitives only and no credential encryption/KEK', () => { const source = read('functions/_lib/crypto.mjs'); for (const name of ['encryptCredential', 'decryptCredential']) assert.doesNotMatch(source, new RegExp(`export\\s+(?:async\\s+)?${name}\\s*`), `unexpected crypto export: ${name}`); assert.doesNotMatch(source, /AES-GCM|AI_CREDENTIAL_KEK|AI_KEY_VERSION/i); });
test('runtime route manifest has no provider endpoint', () => { const routes = JSON.parse(read('_routes.json')); assert.deepEqual(routes.exclude, []); assert.ok(routes.include.every(route => /^\/(?:api|auth|session)(?:\/\*)?$/.test(route))); });
