const assert=require('node:assert/strict');const test=require('node:test');const nodeCrypto=require('node:crypto');
if(!globalThis.crypto)globalThis.crypto=nodeCrypto.webcrypto;
const modules=Promise.all([import('../functions/_lib/http.mjs'),import('../functions/_lib/access-jwt.mjs'),import('../functions/_lib/csrf.mjs'),import('../functions/_lib/crypto.mjs')]);
const env={CF_ACCESS_TEAM_NAME:'team-test',CF_ACCESS_AUD:'aud-1',APP_ORIGIN:'https://app.example',ENVIRONMENT:'production',CSRF_HMAC_KEY:Buffer.alloc(32,7).toString('base64')};
function req(body,headers={}){return new Request('https://app.example/api/x',{method:'POST',headers:{'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});}
test('JSON response security headers and API no-store',async()=>{const [{jsonResponse}]=await modules;const r=jsonResponse({ok:true},{status:200},new Request('https://x.test/api/x'));assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('x-frame-options'),'DENY');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none/);});
test('HTTP safe error codes never expose detail',async()=>{const [{errorResponse}]=await modules;for(const code of [404,405,409,413,415,429]){const r=errorResponse(code);assert.equal(r.status,code);assert.deepEqual(await r.json(),{error:{404:'not_found',405:'method_not_allowed',409:'conflict',413:'payload_too_large',415:'unsupported_media_type',429:'rate_limited'}[code]});assert.equal(r.headers.get('cache-control'),'no-store');}});
test('HTTP invalid statuses and bounded reader options fail safely',async()=>{const [{errorResponse,readJsonBody}]=await modules;for(const code of [399,600,400.5,NaN])assert.equal(errorResponse(code).status,500);await assert.rejects(()=>readJsonBody(req({x:1}),{maxBytes:0}));await assert.rejects(()=>readJsonBody(req({x:1}),{maxBytes:1048577}));});
test('JSON reader rejects pollution, root confusion, depth and size',async()=>{
  const [{readJsonBody}]=await modules;
  const pollution={};Object.defineProperty(pollution,'__proto__',{value:1,enumerable:true});
  for(const body of [pollution,Object.assign({},JSON.parse('{"constructor":1}')),[]]) await assert.rejects(()=>readJsonBody(req(body)));
  const nested={}; let x=nested; for(let i=0;i<25;i++){x.next={};x=x.next;}
  await assert.rejects(()=>readJsonBody(req(nested)));
  const oversized=new Request('https://x/api',{method:'POST',headers:{'content-type':'application/json','content-length':'2000000'},body:'{"x":1}'});
  await assert.rejects(()=>readJsonBody(oversized));
});
test('Crypto retains canonical base64url and digest/HMAC primitives only',async()=>{const [,,,{base64urlEncode,base64urlDecode,sha256,hmacSha256}]=await modules;const encoded=base64urlEncode('safe');assert.equal(new TextDecoder().decode(base64urlDecode(encoded)),'safe');assert.throws(()=>base64urlDecode('A'));assert.equal((await sha256('safe')).length,32);assert.equal((await hmacSha256(new Uint8Array(32),'safe')).length,32);});
test('CSRF binds exact origin, subject, signature, and expiry',async()=>{const [,,{issueCsrfToken,requireCsrf}]=await modules;const token=await issueCsrfToken(env,'sub',1);const good=new Request('https://app.example/api/x',{method:'POST',headers:{Origin:'https://app.example','X-CSRF-Token':token}});await requireCsrf(good,env,'sub');await assert.rejects(()=>requireCsrf(new Request(good,{headers:{Origin:'https://evil.example','X-CSRF-Token':token}}),env,'sub'));const parts=token.split('.');const tampered=`${parts[0]}.${parts[1][0]==='A'?'B':'A'}${parts[1].slice(1)}`;await assert.rejects(()=>requireCsrf(new Request(good,{headers:{Origin:'https://app.example','X-CSRF-Token':tampered}}),env,'sub'));});
test('CSRF local origins and real expiry',async()=>{const [,,{issueCsrfToken,verifyCsrfToken,requireCsrf}]=await modules;const local={...env,APP_ORIGIN:'http://localhost:8788',ENVIRONMENT:'local'};const token=await issueCsrfToken(local,'sub',10);assert.equal(await verifyCsrfToken(token,local,'sub'),true);const old=Date.now;Date.now=()=>old()+11000;try{assert.equal(await verifyCsrfToken(token,local,'sub'),false);}finally{Date.now=old;}await assert.rejects(()=>requireCsrf(new Request('http://localhost:8788/x',{method:'POST',headers:{Origin:'http://localhost:8788','X-CSRF-Token':token}}),{...local,APP_ORIGIN:'http://remote.example'},'sub'));});
test('Access JWT verifies RS256 and performs bounded JWKS fetch',async()=>{const [,{verifyAccessJwt,clearAccessJwksCache}]=await modules;const {publicKey,privateKey}=await new Promise((ok,no)=>nodeCrypto.generateKeyPair('rsa',{modulusLength:2048},(e,pub,priv)=>e?no(e):ok({publicKey:pub,privateKey:priv})));const jwk=publicKey.export({format:'jwk'});jwk.kid='k1';jwk.use='sig';jwk.alg='RS256';const b=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');const claims={iss:'https://team-test.cloudflareaccess.com',aud:['aud-1'],sub:'sub',exp:Math.floor(Date.now()/1000)+60,nbf:Math.floor(Date.now()/1000)-1,iat:Math.floor(Date.now()/1000)};const h=b({alg:'RS256',kid:'k1',typ:'JWT'}),p=b(claims),s=nodeCrypto.createSign('RSA-SHA256').update(`${h}.${p}`).sign(privateKey).toString('base64url');const old=global.fetch;let calls=0;global.fetch=async(url,options)=>{calls++;assert.equal(options.redirect,'error');return new Response(JSON.stringify({keys:[jwk]}),{headers:{'content-type':'application/json'}})};try{const got=await verifyAccessJwt(new Request('https://app/api',{headers:{'Cf-Access-Jwt-Assertion':`${h}.${p}.${s}`}}),env);assert.equal(got.sub,'sub');clearAccessJwksCache();global.fetch=async()=>{throw Error('network down')};await assert.rejects(()=>verifyAccessJwt(new Request('https://app/api',{headers:{'Cf-Access-Jwt-Assertion':`${h}.${p}.${s}`}}),env),/unauthorized|jwks/i);for(const change of [{header:{alg:'none'}},{claims:{aud:['wrong']}},{claims:{iss:'https://evil.cloudflareaccess.com'}},{claims:{exp:0}},{claims:{nbf:9999999999}}]){const hh=b(change.header||{alg:'RS256',kid:'k1',typ:'JWT'}),c={...claims,...(change.claims||{})},pp=b(c),ss=nodeCrypto.createSign('RSA-SHA256').update(`${hh}.${pp}`).sign(privateKey).toString('base64url');await assert.rejects(()=>verifyAccessJwt(new Request('https://app/api',{headers:{'Cf-Access-Jwt-Assertion':`${hh}.${pp}.${ss}`}}),env));}assert.ok(calls<=2);}finally{global.fetch=old;clearAccessJwksCache();}});
test('Access JWT rejects malformed JWKS and throttles forged kids',async()=>{const [,{verifyAccessJwt,clearAccessJwksCache}]=await modules;const old=global.fetch;let calls=0;global.fetch=async()=>{calls++;return new Response(JSON.stringify({keys:[]}),{headers:{'content-type':'application/json'}})};const b=v=>Buffer.from(JSON.stringify(v)).toString('base64url');const c={iss:'https://team-test.cloudflareaccess.com',aud:'aud-1',sub:'s',exp:Math.floor(Date.now()/1000)+60,nbf:0,iat:0};try{for(const kid of ['a','b','c'])await assert.rejects(()=>verifyAccessJwt(new Request('https://x',{headers:{'Cf-Access-Jwt-Assertion':`${b({alg:'RS256',kid})}.${b(c)}.${'A'.repeat(342)}`}}),env));assert.equal(calls,1);}finally{global.fetch=old;clearAccessJwksCache();}});
