'use strict';
const assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path'),{pathToFileURL}=require('node:url'),nodeCrypto=require('node:crypto');
if(!globalThis.crypto)globalThis.crypto=nodeCrypto.webcrypto;
const root=path.join(__dirname,'..');let route,schema,csrf,AppError;const env={APP_ORIGIN:'https://app.example.test/',CSRF_HMAC_KEY:Buffer.alloc(32,7).toString('base64')};
test.before(async()=>{route=await import(pathToFileURL(path.join(root,'functions/api/v1/state.js')).href);schema=await import(pathToFileURL(path.join(root,'functions/_lib/state-schema.mjs')).href);({issueCsrfToken:csrf}=await import(pathToFileURL(path.join(root,'functions/_lib/csrf.mjs')).href));({AppError}=await import(pathToFileURL(path.join(root,'functions/_lib/repositories.mjs')).href));});
const base=()=>({backupType:'full',formatVersion:1}),at='2026-09-02T00:00:00.000Z';
function ctx(repo,request,extra={}){return{request,env,data:{account:{id:'account-1'},repositories:repo,accessClaims:{sub:'subject-1'},requestId:'request-1'},...extra};}
async function headers(){return{'content-type':'application/json',Origin:new URL(env.APP_ORIGIN).origin,'X-CSRF-Token':await csrf(env,'subject-1')};}
function repo(row=null,saved=null){const calls=[];return{calls,async getState(id){calls.push(['get',id]);return row;},async putState(id,x){calls.push(['put',id,x]);return saved;},async appendAuditEvent(x){calls.push(['audit',x]);}};}
async function canon(x){return schema.validateAndCanonicalizeState(x);}
test('GET empty and headers',async()=>{const r=repo(),x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state')));assert.equal(x.status,200);assert.deepEqual(await x.json(),{version:0,state:null,sha256:null,updatedAt:null});assert.equal(x.headers.get('cache-control'),'no-store');assert.equal(x.headers.get('x-content-type-options'),'nosniff');});
test('GET validates canonical payload and hash',async()=>{const s=base(),c=await canon(s),r=repo({version:3,payload_json:c.payloadJson,payload_sha256:c.payloadSha256,updated_at:at}),x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state')));assert.equal(x.status,200);assert.deepEqual(await x.json(),{version:3,state:s,sha256:c.payloadSha256,updatedAt:at});assert.equal((await route.onRequest(ctx(repo({version:3,payload_json:c.payloadJson,payload_sha256:'0'.repeat(64),updated_at:at}),new Request('https://app.example.test/api/v1/state')))).status,500);});
test('PUT create/update contract uses canonical server values',async()=>{const s=base(),c=await canon(s),r=repo(null,{version:1,updated_at:at,payload_json:'bad',payload_sha256:'bad'}),x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:await headers(),body:JSON.stringify({expectedVersion:0,state:s})})));assert.equal(x.status,200);assert.deepEqual(await x.json(),{version:1,state:s,sha256:c.payloadSha256,updatedAt:at});assert.equal(r.calls[0][2].expectedVersion,null);assert.equal(r.calls[0][2].payloadJson,c.payloadJson);await new Promise(setImmediate);assert.ok(r.calls.some(v=>v[0]==='audit'));});
test('PUT rejects conflicts, unknown fields, client hash/user id and bad CSRF',async()=>{const r=repo();r.putState=async()=>{throw new AppError('CONFLICT','stale');};const h=await headers();let x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:JSON.stringify({expectedVersion:1,state:base()})})));assert.equal(x.status,409);x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:JSON.stringify({expectedVersion:0,state:base(),hash:'x'})})));assert.equal(x.status,400);x=await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:0,state:base()})})));assert.equal(x.status,403);});
test('method/body/context/audit failures are safe',async()=>{const r=repo();assert.equal((await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'POST'})))).status,405);const h=await headers();assert.equal((await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:{...h,'content-type':'text/plain'},body:'{}'})))).status,415);assert.equal((await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:'{'})))).status,400);const huge=JSON.stringify({expectedVersion:0,state:base()})+'x'.repeat(1024*1024);assert.equal((await route.onRequest(ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:{...h,'content-length':String(Buffer.byteLength(huge))},body:huge})))).status,413);assert.equal((await route.onRequest({request:new Request('https://app.example.test/api/v1/state'),data:{}})).status,401);assert.equal((await route.onRequest({request:new Request('https://app.example.test/api/v1/state'),data:{account:{id:'account-1'},accessClaims:{sub:'s'}}})).status,500);const s=base(),c=await canon(s),ok=repo(null,{version:1,updated_at:at});ok.appendAuditEvent=async()=>{throw Error('audit')};let x=await route.onRequest(ctx(ok,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:JSON.stringify({expectedVersion:0,state:s})})));assert.equal(x.status,200);assert.equal((await x.json()).sha256,c.payloadSha256);});
test('405 includes Allow and no-store security headers',async()=>{const x=await route.onRequest(ctx(repo(),new Request('https://app.example.test/api/v1/state',{method:'PATCH'})));assert.equal(x.status,405);assert.equal(x.headers.get('allow'),'GET, PUT');assert.equal(x.headers.get('cache-control'),'no-store');assert.equal(x.headers.get('x-content-type-options'),'nosniff');});
test('expectedVersion is safe integer and bounded',async()=>{const h=await headers();for(const v of[-1,1.5,Number.MAX_SAFE_INTEGER+1]){const x=await route.onRequest(ctx(repo(),new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:JSON.stringify({expectedVersion:v,state:base()})})));assert.equal(x.status,400);}});
test('GET rejects malformed, noncanonical, and invalid metadata records',async()=>{const s=base(),c=await canon(s),cases=[{version:1,payload_json:'{',payload_sha256:c.payloadSha256,updated_at:at},{version:1,payload_json:'{"formatVersion":1,"backupType":"full"}',payload_sha256:c.payloadSha256,updated_at:at},{version:0,payload_json:c.payloadJson,payload_sha256:c.payloadSha256,updated_at:at},{version:1,payload_json:c.payloadJson,payload_sha256:c.payloadSha256,updated_at:'bad'}];for(const row of cases)assert.equal((await route.onRequest(ctx(repo(row),new Request('https://app.example.test/api/v1/state')))).status,500);});
test('audit is best effort with waitUntil and unknown errors stay generic',async()=>{const s=base(),h=await headers(),saved={version:1,updated_at:at};let seen=[];const r=repo(null,saved);r.appendAuditEvent=async()=>{throw Error('secret audit detail')};const c=ctx(r,new Request('https://app.example.test/api/v1/state',{method:'PUT',headers:h,body:JSON.stringify({expectedVersion:0,state:s})}),{waitUntil:p=>seen.push(p)});let x=await route.onRequest(c);assert.equal(x.status,200);assert.equal(seen.length,1);await seen[0];const bad=repo();bad.getState=async()=>{throw Error('database secret detail')};x=await route.onRequest(ctx(bad,new Request('https://app.example.test/api/v1/state')));assert.equal(x.status,500);assert.doesNotMatch(await x.text(),/secret detail/);});
