const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const client=read('js/food-ai-client.js'),app=read('js/app.js'),sw=read('service-worker.js'),index=read('index.html');
test('Food AI bounds and strict decoding',()=>{for(const s of ['MAX_SOURCE','MAX_IMAGE','MAX_REQUEST','MAX_RESPONSE','TextDecoder','fatal: true','content-length','reader.cancel','Number.isFinite','value < 0','bitmap?.close?.()','no-store','referrerPolicy'])assert.ok(client.includes(s),s);assert.doesNotMatch(client,/baseURL/);assert.doesNotMatch(client,/console\.(log|error).*apiKey/)});
test('UI provider selection, exact OpenAI Luna model, and no file/key persistence',()=>{assert.match(app,/\['gemini','openai'\]/);assert.match(app,/foodGeminiModel/);assert.match(app,/provider === 'openai' \? 'gpt-5\.6-luna'/);assert.match(app,/gpt-5\.6-luna/);assert.doesNotMatch(app,/gpt-5\.6-luna-evil/);assert.doesNotMatch(app,/TSBQwenFoodAIClient/);assert.match(app,/input\.value=''/);assert.match(app,/requestId/);assert.match(app,/ai\.requestId!==requestId/);assert.doesNotMatch(app,/localStorage[\s\S]{0,300}(?:apiKey|API key)/i)});
test('SW cross-origin bypass and exact Gemini CSP',()=>{assert.match(sw,/url\.origin!==self\.location\.origin\)return/);assert.match(sw,/sensitiveRoots=\['\/api','\/auth','\/session'\]/);const csp=index.match(/Content-Security-Policy" content="([^"]+)/)[1];assert.match(csp,/connect-src 'self' https:\/\/generativelanguage\.googleapis\.com/);assert.doesNotMatch(csp,/connect-src[^;]*(?:\*|data:|blob:)/)});
