const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../js/food-ai-client.js'),'utf8'),KEY='AIzaSyA-test-key-123456789',AC=globalThis.AbortController;
const food={name:'Soup',ingredients:['water'],portionGrams:300,volumeMl:null,calories:120,protein:5,fat:3,carbs:15,comment:'approximate',confidence:.7};
function h({status=200,data=food,body,headers={},bitmap={width:100,height:100},reader,canvas,fetchImpl}={}){let req,closed=0,drawn=0;const payload=body??JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(data)}]}}]});class FR{readAsDataURL(){if(reader==='error')return this.onerror();this.result=reader==='bad'?'data:image/jpeg;base64,%%%':'data:image/jpeg;base64,YWJj';this.onload()}}const b={...bitmap,close(){closed++}},c=canvas||{getContext:()=>({drawImage(){drawn++}}),toBlob:cb=>cb(new Blob(['abc'],{type:'image/jpeg'}))};const w={Blob,FileReader:FR,AbortController:AC,setTimeout,clearTimeout,TextDecoder,createImageBitmap:async()=>b,document:{createElement:()=>c},fetch:async(u,o)=>{req={u,o};return fetchImpl?fetchImpl(u,o):{ok:status===200,status,headers:{get:k=>headers[k]??(k==='content-type'?'application/json':k==='content-length'?String(Buffer.byteLength(payload)):'')},body:null,text:async()=>payload}}};vm.runInNewContext(src,{window:w,globalThis:w,Blob,FileReader:FR,AbortController:AC,setTimeout,clearTimeout,TextDecoder});return{w,get:()=>req,stats:()=>({closed,drawn})}}
const file=()=>new Blob(['x'],{type:'image/jpeg'});const bad=async(hh,o,c)=>assert.rejects(()=>hh.w.TSBFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY,...o}),e=>e.code===c);
test('browser globals/request contract/bitmap close',async()=>{const x=h();const r=await x.w.TSBFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY});const q=x.get(),b=JSON.parse(q.o.body);assert.equal(r.name,'Soup');assert.match(q.u,/^https:\/\/generativelanguage\.googleapis\.com\/v1beta\/models\/gemini-3\.8-flash:generateContent$/);assert.equal(q.o.headers['x-goog-api-key'],KEY);assert(!q.u.includes(KEY));assert(!q.o.body.includes(KEY));assert.equal(q.o.cache,'no-store');assert.equal(q.o.referrerPolicy,'no-referrer');assert.equal(b.generationConfig.responseMimeType,'application/json');assert.deepEqual(x.stats(),{closed:1,drawn:1})});
test('image spoof/decode/zero-dimension/draw/toBlob/FileReader failures',async()=>{await bad(h(),{file:new Blob(['x'],{type:'image/gif'})},'INVALID_IMAGE');await bad(h(),{file:new Blob([Buffer.alloc(10*1024*1024+1)],{type:'image/jpeg'})},'IMAGE_TOO_LARGE');await bad(h({reader:'error'}),{},'INVALID_IMAGE');await bad(h({reader:'bad'}),{},'INVALID_IMAGE');await bad(h({bitmap:{width:0,height:100}}),{},'INVALID_IMAGE');await bad(h({canvas:{getContext:()=>({drawImage(){throw Error()}}),toBlob(){}}}),{},'INVALID_IMAGE');await bad(h({canvas:{getContext:()=>({drawImage(){}}),toBlob:cb=>cb(null)}}),{},'INVALID_IMAGE')});
test('status/limits/schema/number validation',async()=>{for(const [s,c]of [[401,'AUTH'],[403,'AUTH'],[429,'QUOTA'],[500,'API']])await bad(h({status:s}),{},c);await bad(h({headers:{'content-length':'abc'}}),{},'INVALID_RESPONSE');await bad(h({headers:{'content-length':'524289'}}),{},'INVALID_RESPONSE');for(const v of [{candidates:[]},{candidates:[{},{}]},{candidates:[{content:{parts:[]}}]},{candidates:[{content:{parts:[{text:'x'},{text:'y'}]}}]}])await bad(h({body:JSON.stringify(v)}),{},'INVALID_RESPONSE');for(const k of ['calories','protein','fat','carbs'])for(const v of [NaN,-1,Infinity,50001])await bad(h({data:{...food,[k]:v}}),{},'INVALID_RESPONSE');await bad(h({data:{...food,unknown:1}}),{},'INVALID_RESPONSE')});
test('external abort before preparation prevents fetch; model injection rejected',async()=>{const ac=new AC();ac.abort();let calls=0;const x=h({fetchImpl:async()=>{calls++;throw Error()}});await assert.rejects(()=>x.w.TSBFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY,signal:ac.signal}),e=>e.code==='ABORTED');assert.equal(calls,0);await bad(h(),{model:'https://evil.test'},'API');for(const k of ['', 'short','a'.repeat(4097),'bad key'])await assert.rejects(()=>h().w.TSBFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:k}),e=>e.code==='NO_KEY')});
