const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../js/openai-food-ai-client.js'),'utf8'),AC=AbortController,KEY='openai-test-key-123';
const food={name:'Soup',ingredients:['water'],portionGrams:300,volumeMl:null,calories:120,protein:5,fat:3,carbs:15,comment:'approximate',confidence:.7};
function envelope(){return {status:'completed',output:[{type:'reasoning',id:'r1',status:'completed',summary:[]},{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(food)}]}]};}
function env({blobSize=100,fetchImpl,timer}={}){let req,stats={};class FR{readAsDataURL(){this.result='data:image/jpeg;base64,YWJj';this.onload()}}const bitmap={width:2000,height:1000,close(){stats.closed=(stats.closed||0)+1}},canvas={width:0,height:0,getContext:()=>({drawImage(){stats.draw=[canvas.width,canvas.height]}}),toBlob:(cb,t,q)=>{stats.quality=[t,q];cb(new Blob([Buffer.alloc(blobSize)],{type:'image/jpeg'}))}};const w={Blob,FileReader:FR,AbortController,setTimeout:timer||setTimeout,clearTimeout,TextDecoder,createImageBitmap:async()=>bitmap,document:{createElement:()=>canvas},fetch:async(u,o)=>{req={u,o};return fetchImpl?fetchImpl(u,o):{ok:true,status:200,headers:{get:k=>k==='content-type'?'application/json':k==='content-length'?String(Buffer.byteLength(JSON.stringify(envelope()))):''},body:null,text:async()=>JSON.stringify(envelope())}}};vm.runInNewContext(src,{window:w,Blob,FileReader:FR,AbortController,setTimeout:timer||setTimeout,clearTimeout,TextDecoder});return{w,get:()=>req,stats};}
const file=()=>new Blob(['x'],{type:'image/jpeg'});
test('happy path, exact Responses transport and compression',async()=>{const x=env();assert.deepEqual(JSON.parse(JSON.stringify(await x.w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY}))),food);const q=x.get();assert.equal(q.u,'https://api.openai.com/v1/responses');assert.equal(q.o.headers.Authorization,'Bearer '+KEY);assert.equal(q.o.cache,'no-store');assert.equal(q.o.referrerPolicy,'no-referrer');const b=JSON.parse(q.o.body);assert.equal(b.model,'gpt-5.6-luna');assert.deepEqual(b.reasoning,{effort:'low'});assert.equal(b.input[0].content[1].type,'input_image');assert.equal(b.input[0].content[1].detail,'low');assert.equal(b.text.format.type,'json_schema');assert.equal(b.store,false);assert(!q.o.body.includes('openai-test-key-123'));assert.deepEqual(x.stats.draw,[1280,640]);assert.deepEqual(x.stats.quality,['image/jpeg',.78]);assert.equal(x.stats.closed,1)});
test('prepared image limit and model injection',async()=>{await assert.rejects(()=>env({blobSize:3*1024*1024+1}).w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY}),e=>e.code==='IMAGE_TOO_LARGE');await assert.rejects(()=>env().w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY,model:'gpt-5.6-luna evil'}),e=>e.code==='API');});
test('timeout without waiting and external abort',async()=>{let fire;const x=env({timer:fn=>{fire=fn;return 1},fetchImpl:(_,o)=>new Promise((_,rej)=>o.signal.addEventListener('abort',()=>{const e=new Error();e.name='AbortError';rej(e)}))});const p=x.w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY});while(!fire)await Promise.resolve();fire();await assert.rejects(p,e=>e.code==='TIMEOUT');const c=new AbortController(),y=env({fetchImpl:(_,o)=>new Promise((_,rej)=>o.signal.addEventListener('abort',()=>{const e=new Error();e.name='AbortError';rej(e)}))});const z=y.w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY,signal:c.signal});while(!y.get())await Promise.resolve();c.abort();await assert.rejects(z,e=>e.code==='ABORTED');});
test('incomplete, failed and extra message responses are rejected',async()=>{for(const response of [{status:'incomplete',output:[]},{status:'failed',output:[]},{status:'completed',output:[{type:'message',role:'assistant',status:'completed',content:[]},{type:'message',role:'assistant',status:'completed',content:[]}]}]){const x=env({fetchImpl:async()=>({ok:true,headers:{get:k=>k==='content-type'?'application/json':''},body:null,text:async()=>JSON.stringify(response)})});await assert.rejects(()=>x.w.TSBOpenAIFoodAIClient.analyzeFoodPhoto({file:file(),apiKey:KEY}),e=>e.code==='INVALID_RESPONSE');}});
