import { base64urlDecode } from './crypto.mjs';
const MAX_TOKEN=16384,MAX_KID=256,MAX_KEYS=16,MAX_JWKS=262144,SKEW=60,INTERVAL=300000,FAIL_TTL=5000,MAX_CACHES=4;const caches=new Map();
const epoch=()=>Math.floor(Date.now()/1000);const slug=e=>{const s=String(e?.CF_ACCESS_TEAM_NAME||'');if(!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(s))throw Error('invalid team');return s;};
const part=s=>{const b=base64urlDecode(s);if(b.length>32768)throw Error('invalid jwt');let x;try{x=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(b));}catch{throw Error('invalid jwt');}if(!x||typeof x!=='object'||Array.isArray(x)||Object.getPrototypeOf(x)!==Object.prototype)throw Error('invalid jwt');return x;};
async function fetchKeys(issuer){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),5000);let r;try{r=await fetch(`${issuer}/cdn-cgi/access/certs`,{headers:{accept:'application/json'},redirect:'error',signal:ac.signal});}catch{throw Error('jwks unavailable');}finally{clearTimeout(timer);}const ct=r.headers.get('content-type')||'',len=r.headers.get('content-length');if(!r.ok||!/^application\/json(?:\s*;|$)/i.test(ct)||(len&&(!/^\d+$/.test(len)||Number(len)>MAX_JWKS)))throw Error('invalid jwks response');const rd=r.body?.getReader();if(!rd)throw Error('invalid jwks body');const cs=[];let n=0;try{for(;;){const x=await rd.read();if(x.done)break;n+=x.value.byteLength;if(n>MAX_JWKS){await rd.cancel();throw Error('large jwks');}cs.push(x.value);}}catch(e){try{await rd.cancel();}catch{}throw e;}finally{try{rd.releaseLock();}catch{}}const b=new Uint8Array(n);let p=0;for(const c of cs){b.set(c,p);p+=c.length;}let d;try{d=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(b));}catch{throw Error('invalid jwks');}if(!d||!Array.isArray(d.keys)||d.keys.length>MAX_KEYS)throw Error('invalid jwks shape');const keys=new Map();for(const k of d.keys){if(!k||typeof k!=='object'||typeof k.kid!=='string'||k.kid.length<1||k.kid.length>MAX_KID||typeof k.n!=='string'||k.n.length<1||k.n.length>4096||typeof k.e!=='string'||k.e.length<1||k.e.length>64||k.kty!=='RSA'||k.alg!=='RS256'||k.use!=='sig'||keys.has(k.kid))throw Error('invalid jwks key');try{keys.set(k.kid,await crypto.subtle.importKey('jwk',k,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']));}catch{throw Error('invalid jwks key');}}if(!keys.size)throw Error('no usable jwks keys');return keys;}
export function clearAccessJwksCache(){caches.clear();}
function put(issuer,c){if(caches.size>=MAX_CACHES&&!caches.has(issuer))caches.delete(caches.keys().next().value);caches.set(issuer,c);}
async function keysFor(issuer,kid){let c=caches.get(issuer),t=Date.now();if(!c||c.expires<=t){let keys;try{keys=await fetchKeys(issuer);}catch(e){c={keys:new Map(),expires:t+FAIL_TTL,forcedAt:t,negative:new Set([kid])};put(issuer,c);throw e;}c={keys,expires:t+INTERVAL,forcedAt:0,negative:new Set()};put(issuer,c);}if(c.keys.has(kid))return c.keys.get(kid);if(c.negative.has(kid))return null;if(t-c.forcedAt<INTERVAL){c.negative.add(kid);return null;}c.forcedAt=t;let keys;try{keys=await fetchKeys(issuer);}catch(e){c.negative.add(kid);throw e;}c.keys=keys;c.expires=t+INTERVAL;c.negative.clear();if(!keys.has(kid))c.negative.add(kid);return keys.get(kid)||null;}
export async function verifyAccessJwt(request,env){const token=request?.headers?.get('Cf-Access-Jwt-Assertion');if(!token||token.length>MAX_TOKEN)throw Error('unauthorized');const a=token.split('.');if(a.length!==3)throw Error('unauthorized');const h=part(a[0]),c=part(a[1]);if(h.alg!=='RS256'||typeof h.kid!=='string'||h.kid.length<1||h.kid.length>MAX_KID)throw Error('unauthorized');const issuer=`https://${slug(env)}.cloudflareaccess.com`,aud=String(env?.CF_ACCESS_AUD||'');if(!aud||aud.length>256||/[\u0000-\u001f\u007f]/.test(aud)||c.iss!==issuer||!((typeof c.aud==='string'?[c.aud]:Array.isArray(c.aud)?c.aud:[]).some(x=>x===aud)))throw Error('unauthorized');const t=epoch();for(const x of ['exp','nbf','iat'])if(!Number.isInteger(c[x]))throw Error('unauthorized');if(c.exp<t-SKEW||c.nbf>t+SKEW||c.iat>t+SKEW||c.iat<0||typeof c.sub!=='string'||!c.sub||c.sub.length>512||/[\u0000-\u001f\u007f]/.test(c.sub))throw Error('unauthorized');const sig=base64urlDecode(a[2]);if(sig.length<256||sig.length>1024)throw Error('unauthorized');const key=await keysFor(issuer,h.kid);if(!key)throw Error('unauthorized');let ok=false;try{ok=await crypto.subtle.verify({name:'RSASSA-PKCS1-v1_5'},key,sig,new TextEncoder().encode(`${a[0]}.${a[1]}`));}catch{}if(!ok)throw Error('unauthorized');return c;}
export const verifyJwt=verifyAccessJwt;
