import { base64urlEncode,base64urlDecode,hmacSha256,verifyHmacSha256 } from './crypto.mjs';
const METHODS=new Set(['POST','PUT','PATCH','DELETE']),TTL=900,SKEW=30;
function raw(env){const s=String(env?.CSRF_HMAC_KEY||'');if(!/^[A-Za-z0-9+/]+={0,2}$/.test(s))throw Error('invalid csrf key');const b=atob(s);if(b.length<32||b.length>128)throw Error('invalid csrf key');return Uint8Array.from(b,c=>c.charCodeAt(0));}
function origin(env){const s=String(env?.APP_ORIGIN||'');let u;try{u=new URL(s);}catch{throw Error('invalid origin');}const local=['localhost','127.0.0.1','[::1]'].includes(u.hostname);if((u.protocol!=='https:'&&!(local&&env?.ENVIRONMENT==='local'&&u.protocol==='http:'))||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('invalid origin');return u.origin;}
async function hkey(env){return crypto.subtle.importKey('raw',raw(env),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
export async function issueCsrfToken(env,sub,ttl=TTL){if(typeof sub!=='string'||!sub||sub.length>512||!Number.isFinite(ttl)||!Number.isInteger(ttl)||ttl<1||ttl>TTL)throw Error('invalid csrf ttl');const exp=Math.floor(Date.now()/1000)+ttl,p=base64urlEncode(JSON.stringify({sub,exp}));return `${p}.${base64urlEncode(await hmacSha256(await hkey(env),p))}`;}
export async function verifyCsrfToken(token,env,sub){if(typeof token!=='string'||token.length>2048||typeof sub!=='string')return false;const a=token.split('.');if(a.length!==2)return false;let p;try{p=JSON.parse(new TextDecoder().decode(base64urlDecode(a[0])));}catch{return false;}const t=Math.floor(Date.now()/1000);if(!p||Object.keys(p).length!==2||!Object.prototype.hasOwnProperty.call(p,'sub')||!Object.prototype.hasOwnProperty.call(p,'exp')||p.sub!==sub||!Number.isInteger(p.exp)||p.exp<t||p.exp>t+TTL+SKEW)return false;try{return await verifyHmacSha256(await hkey(env),a[0],base64urlDecode(a[1]));}catch{return false;}}
export async function requireCsrf(request,env,access){if(!METHODS.has(request.method.toUpperCase()))return;const sub=typeof access==='string'?access:access?.sub;if(request.headers.get('Origin')!==origin(env)||!await verifyCsrfToken(request.headers.get('X-CSRF-Token')||'',env,sub))throw Error('csrf rejected');}
export const validateCsrf=requireCsrf;
