const MAX_BODY = 1024 * 1024, MAX_DEPTH = 20, MAX_NODES = 10000, MAX_STRING = 65536;
const CSP = "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-src 'none'; worker-src 'self'; manifest-src 'self'; frame-ancestors 'none';";
const headers = { 'Content-Security-Policy': CSP, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=()', 'Cross-Origin-Opener-Policy': 'same-origin', 'X-Frame-Options': 'DENY' };
export function securityHeaders(init = {}) { const h = new Headers(init); for (const [k,v] of Object.entries(headers)) h.set(k,v); return h; }
export function jsonResponse(data, init = {}) { const h = securityHeaders(init.headers); h.set('Content-Type','application/json; charset=utf-8'); h.set('Cache-Control','no-store'); return new Response(JSON.stringify(data), { ...init, headers:h }); }
export function errorResponse(status = 500) { const valid=Number.isInteger(status)&&status>=400&&status<=599; const actual=valid?status:500; const code = ({400:'bad_request',401:'unauthorized',403:'forbidden',404:'not_found',405:'method_not_allowed',409:'conflict',413:'payload_too_large',415:'unsupported_media_type',429:'rate_limited'})[actual] || (actual >= 500 ? 'internal_error' : 'bad_request'); return jsonResponse({ error: code }, { status:actual }); }
function validate(value) { let nodes=0; function walk(v, depth) { if (++nodes > MAX_NODES || depth > MAX_DEPTH) throw new Error('bounds'); if (typeof v === 'string' && v.length > MAX_STRING) throw new Error('string'); if (v && typeof v === 'object') { if (Object.getPrototypeOf(v) !== Object.prototype && !Array.isArray(v)) throw new Error('object'); for (const k of Object.keys(v)) { if (FORBIDDEN.has(k) || k.length > 256) throw new Error('key'); walk(v[k], depth+1); } } } const root = value; if (!root || typeof root !== 'object' || Array.isArray(root) || Object.getPrototypeOf(root) !== Object.prototype) throw new Error('root'); walk(root,0); return root; }
const FORBIDDEN = new Set(['__proto__','prototype','constructor']);
export async function readJsonBody(request, { maxBytes = MAX_BODY } = {}) { if (!(request instanceof Request) || !Number.isInteger(maxBytes) || maxBytes < 1 || maxBytes > MAX_BODY) throw new Error('request'); const type = request.headers.get('content-type') || ''; if (!/^application\/json(?:\s*;\s*charset\s*=\s*(?:utf-8|us-ascii))?\s*$/i.test(type)) throw Error('content-type'); const length = request.headers.get('content-length'); if (length && (!/^\d+$/.test(length) || Number(length) > maxBytes)) throw Error('size'); const reader=request.body?.getReader(); if(!reader)throw Error('body'); const chunks=[];let total=0;try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>maxBytes) { await reader.cancel(); throw Error('size'); } chunks.push(part.value); }}catch(e){try{await reader.cancel();}catch{}throw e;}finally{try{reader.releaseLock();}catch{}}const all=new Uint8Array(total);let p=0;for(const c of chunks){all.set(c,p);p+=c.length;}let parsed;try{parsed=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(all));}catch{throw Error('json');}return validate(parsed); }
