export class AppError extends Error {
  constructor(code, message) { super(message); this.name = 'AppError'; this.code = code; }
}
export const ErrorCodes = Object.freeze({ INVALID_INPUT: 'INVALID_INPUT', NOT_FOUND: 'NOT_FOUND', CONFLICT: 'CONFLICT', FORBIDDEN: 'FORBIDDEN', DB_ERROR: 'DB_ERROR' });
export const AUDIT_EVENT_TYPES = Object.freeze(['user.created', 'state.updated']);
const ID = /^[A-Za-z0-9_-]{1,128}$/; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const HASH = /^[a-f0-9]{64}$/; const BASE64URL = /^[A-Za-z0-9_-]+$/; const REQUEST = /^[A-Za-z0-9._:-]{1,256}$/;
const text = (v, name, max) => { if (typeof v !== 'string' || v.length < 1 || v.length > max) throw new AppError(ErrorCodes.INVALID_INPUT, `${name} is invalid`); return v; };
const id = (v, name = 'id') => { text(v, name, 128); if (!ID.test(v)) throw new AppError(ErrorCodes.INVALID_INPUT, `${name} is invalid`); return v; };
const timestamp = v => { text(v, 'timestamp', 24); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)) throw new AppError(ErrorCodes.INVALID_INPUT, 'timestamp is invalid'); const d = new Date(v); if (!Number.isFinite(d.getTime()) || d.toISOString() !== v) throw new AppError(ErrorCodes.INVALID_INPUT, 'timestamp is invalid'); return v; };
const dbError = e => { if (e instanceof AppError) throw e; throw new AppError(ErrorCodes.DB_ERROR, 'database operation failed'); };
const newId = () => { const value = globalThis.crypto?.randomUUID?.(); if (!value || !UUID.test(value)) throw new AppError(ErrorCodes.DB_ERROR, 'secure UUID is unavailable'); return value; };

export function createRepositories(db) {
  if (!db || typeof db.prepare !== 'function') throw new TypeError('D1 database is required');
  const q = (sql, ...binds) => db.prepare(sql).bind(...binds);
  return {
    async ensureUserFromAccess(subject, email, now) { try { const sub = text(subject, 'subject', 512); const at = timestamp(now); let normalized = null; if (email != null) { normalized = email.trim().toLowerCase(); if (normalized.length > 320 || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(normalized)) throw new AppError(ErrorCodes.INVALID_INPUT, 'email is invalid'); } const record = await q('INSERT INTO users (id, access_sub, email, created_at, last_seen_at) VALUES (?, ?, ?, ?, ?) ON CONFLICT(access_sub) DO UPDATE SET email = COALESCE(excluded.email, users.email), last_seen_at = excluded.last_seen_at RETURNING id, access_sub, email, created_at, last_seen_at', newId(), sub, normalized, at, at).first(); if (!record) throw new AppError(ErrorCodes.DB_ERROR, 'user upsert returned no row'); return record; } catch (e) { dbError(e); } },
    async getUserBySubject(subject) { try { return await q('SELECT id, access_sub, email, created_at, last_seen_at FROM users WHERE access_sub = ?', text(subject, 'subject', 512)).first(); } catch (e) { dbError(e); } },
    async getState(userId) { try { id(userId, 'userId'); return await q('SELECT user_id, version, payload_json, payload_sha256, updated_at FROM user_state WHERE user_id = ?', userId).first(); } catch (e) { dbError(e); } },
    async putState(userId, { expectedVersion, payloadJson, payloadSha256, now }) { try { id(userId, 'userId'); timestamp(now); text(payloadJson, 'payloadJson', 1048576); try { JSON.parse(payloadJson); } catch { throw new AppError(ErrorCodes.INVALID_INPUT, 'payloadJson is invalid'); } if (!HASH.test(payloadSha256)) throw new AppError(ErrorCodes.INVALID_INPUT, 'payloadSha256 is invalid'); if (expectedVersion !== null && (!Number.isInteger(expectedVersion) || expectedVersion < 1)) throw new AppError(ErrorCodes.INVALID_INPUT, 'expectedVersion is invalid'); const statement = expectedVersion === null ? 'INSERT INTO user_state (user_id, version, payload_json, payload_sha256, updated_at) SELECT ?, 1, ?, ?, ? WHERE EXISTS (SELECT 1 FROM users WHERE id = ?) RETURNING user_id, version, payload_json, payload_sha256, updated_at' : 'UPDATE user_state SET version = version + 1, payload_json = ?, payload_sha256 = ?, updated_at = ? WHERE user_id = ? AND version = ? RETURNING user_id, version, payload_json, payload_sha256, updated_at'; const binds = expectedVersion === null ? [userId, payloadJson, payloadSha256, now, userId] : [payloadJson, payloadSha256, now, userId, expectedVersion]; const record = await q(statement, ...binds).first(); if (!record) throw new AppError(ErrorCodes.CONFLICT, 'state version conflict'); return record; } catch (e) { dbError(e); } },
    async appendAuditEvent({ id: eventId = newId(), userId = null, eventType, now, requestId }) { try { if (userId !== null) id(userId, 'userId'); id(eventId, 'eventId'); if (!AUDIT_EVENT_TYPES.includes(eventType)) throw new AppError(ErrorCodes.INVALID_INPUT, 'event type is invalid'); timestamp(now); if (typeof requestId !== 'string' || !REQUEST.test(requestId)) throw new AppError(ErrorCodes.INVALID_INPUT, 'requestId is invalid'); await q('INSERT INTO audit_events (id, user_id, event_type, created_at, request_id) VALUES (?, ?, ?, ?, ?)', eventId, userId, eventType, now, requestId).run(); return eventId; } catch (e) { dbError(e); } }
  };
}
